# ==============================================================
# = Eureka Peer3 Parameters
# ==============================================================
spring:
  application:
    name: EurekaPeer3

server:
  port: 8767

eureka:
  instance:
    hostname: localhost
    metadataMap:
      zone: zone3
      preferIpAddress: true
      instanceId: ${spring.application.name}-{server.port}

  client:
    serviceUrl:
      defaultZone: http://peer2:8766/eureka/, http://peer1:8765/eureka/