# ==============================================================
# = Eureka Peer3 Parameters
# ==============================================================
spring:
  application:
    name: EshopEureka

server:
  port: 8763

eureka:
  instance:
    hostname: EshopEureka
    metadataMap:
      zone: zone1
      preferIpAddress: true
      instanceId: ${spring.application.name}-{server.port}

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/