# ==============================================================
# = Eureka Parameters
# ==============================================================
spring:
  application:
    name: Eureka

server:
  port: 8761
  tomcat:
    threads:
      max: 5

eureka:
  instance:
    hostname: localhost
    preferIpAddress: false

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
