# ==============================================================
# = Eureka Peer1 Parameters
# ==============================================================
spring:
  application:
    name: EurekaPeer1

server:
  port: 8765

eureka:
  instance:
    hostname: localhost
    metadataMap:
      zone: zone1
      preferIpAddress: true
      instanceId: ${spring.application.name}-{server.port}

  client:
    serviceUrl:
      defaultZone: http://localhost:8766/eureka/, http://localhost:8767/eureka/