# ==============================================================
# = Eureka Peer2 Parameters
# ==============================================================
spring:
  application:
    name: peer2

server:
  port: 8766

eureka:
  instance:
    hostname: peer2
    metadataMap:
      zone: zone2
      preferIpAddress: true
      instanceId: ${spring.application.name}-{server.port}

  client:
    serviceUrl:
      defaultZone: http://peer1:8765/eureka/, http://peer3:8767/eureka/