# ==============================================================
# = Eureka Peer1 Parameters
# ==============================================================
spring:
  application:
    name: EurekaServer

server:
  port: 8761

eureka:
  instance:
    hostname: peer1
    metadataMap:
      zone: zone1
      preferIpAddress: true
      instanceId: ${spring.application.name}-{server.port}

  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/, http://localhost:8763/eureka/